//************************************************************************************
//**  
//**  File name:     G:\group_proj\pic1_REV.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Wednesday, August 13, 2014 13:43:13
//**  Licence:       50 User
//**  Registered to: BCITETCC2012
//**  Licence key:   91DZ5U
//**  
//**  
//**     NOT FOR COMMERCIAL USE
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F877
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_30
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 19660800
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f72
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f72);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_E();
void FCM_E2();
void FCM_E3();
void FCM_E4();
void FCM_E5();
void FCM_E6();
void FCM_E7();
void FCM_E8();
void FCM_F();
void FCM_F2();
void FCM_F3();
void FCM_F5();
void FCM_F6();
void FCM_F7();
void FCM_F8();
void FCM_F4();
void FCM_Input_Switches();
void FCM_Octave1();
void FCM_Octave2();
void FCM_quarter();
void FCM_MiSi();
void FCM_MiFaReRe();
void FCM_DoDoDo();
void FCM_DoDo2();
void FCM_FaDoTrans();
void FCM_intro();
void FCM_DEMO();
void FCM_SFX();
void FCM_PLAY();
void FCM_LCD();


//Variable declarations
#define FCV_TRUE (1)
#define FCV_FALSE (0)
MX_UINT8 FCV_SW7;
MX_UINT8 FCV_TSW6;
MX_UINT8 FCV_SW8;
MX_UINT8 FCV_TSW7;
MX_UINT8 FCV_TSW8;
MX_UINT8 FCV_DEMO;
MX_UINT8 FCV_PLAY;
MX_UINT8 FCV_SEL;
MX_UINT8 FCV_SW1;
MX_UINT8 FCV_SW2;
MX_UINT8 FCV_TSW1;
MX_UINT8 FCV_SW3;
MX_UINT8 FCV_TSW2;
MX_UINT8 FCV_SW4;
MX_UINT8 FCV_TSW3;
MX_UINT8 FCV_DELAY;
MX_UINT8 FCV_SW5;
MX_UINT8 FCV_TSW4;
MX_UINT8 FCV_SW6;
MX_UINT8 FCV_TSW5;
MX_UINT8 FCV_SFX;

MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;
MX_UINT8 FCLV_LOOP4;
MX_UINT8 FCLV_LOOP5;
MX_UINT8 FCLV_LOOP6;
MX_UINT8 FCLV_LOOP7;
MX_UINT8 FCLV_LOOP8;
MX_UINT8 FCLV_LOOP9;
MX_UINT8 FCLV_LOOP10;
MX_UINT8 FCLV_LOOP11;
MX_UINT8 FCLV_LOOP12;
MX_UINT8 FCLV_LOOP13;
MX_UINT8 FCLV_LOOP14;
MX_UINT8 FCLV_LOOP15;
MX_UINT8 FCLV_LOOP16;
MX_UINT8 FCLV_LOOP17;
MX_UINT8 FCLV_LOOP18;
MX_UINT8 FCLV_LOOP19;
MX_UINT8 FCLV_LOOP20;
MX_UINT8 FCLV_LOOP21;
MX_UINT8 FCLV_LOOP22;
MX_UINT8 FCLV_LOOP23;
MX_UINT8 FCLV_LOOP24;
MX_UINT8 FCLV_LOOP25;
MX_UINT8 FCLV_LOOP26;
MX_UINT8 FCLV_LOOP27;
MX_UINT8 FCLV_LOOP28;
MX_UINT8 FCLV_LOOP29;
MX_UINT8 FCLV_LOOP30;
MX_UINT8 FCLV_LOOP31;
MX_UINT8 FCLV_LOOP32;



//LCDDisplay(0): //Defines:

/**** Macro Substitutions ****
a = Unique Component Reference Number
b = D1 Port Letter
c = D2 Port Letter
d = D3 Port Letter
e = D4 Port Letter
f = RS Port Letter
g = E Port Letter
h = Data 1_Pin
i = Data 2 Pin
j = Data 3 Pin
k = Data 4 Pin
l = RS Pin
m = Enable Pin
n = Row Count
o = Column Count
******************************/

	//component connections
	//Port pin lat workaround for 8-bit PIC devices running >= 32MHz
	//seems we need this mod for 19660800 16F1937 so changed to >= 16MHz

  #ifdef FC_CAL_PIC
   #if MX_CLK_SPEED >= 32000000
	#define LCD_4__PORT0    lata
	#define LCD_4__PORT1    lata
	#define LCD_4__PORT2    lata
	#define LCD_4__PORT3    lata
	#define LCD_4__PORT4    lata
	#define LCD_4__PORT5    lata
   #else
    #ifdef MX_LCD_PORT_LAT
	 #define LCD_4__PORT0    lata
	 #define LCD_4__PORT1    lata
	 #define LCD_4__PORT2    lata
	 #define LCD_4__PORT3    lata
	 #define LCD_4__PORT4    lata
	 #define LCD_4__PORT5    lata
    #else
	 #define LCD_4__PORT0    porta
	 #define LCD_4__PORT1    porta
	 #define LCD_4__PORT2    porta
	 #define LCD_4__PORT3    porta
	 #define LCD_4__PORT4    porta
	 #define LCD_4__PORT5    porta
	#endif
   #endif
  #else
	#define LCD_4__PORT0    porta
	#define LCD_4__PORT1    porta
	#define LCD_4__PORT2    porta
	#define LCD_4__PORT3    porta
	#define LCD_4__PORT4    porta
	#define LCD_4__PORT5    porta
  #endif

	#define LCD_4__TRIS0    trisa
	#define LCD_4__TRIS1    trisa
	#define LCD_4__TRIS2    trisa
	#define LCD_4__TRIS3    trisa
	#define LCD_4__TRIS4    trisa
	#define LCD_4__TRIS5    trisa
	#define LCD_4__BIT0    	0
	#define LCD_4__BIT1    	1
	#define LCD_4__BIT2    	2
	#define LCD_4__BIT3    	3
	#define LCD_4__RS      	4
	#define LCD_4__E       	5
	#define LCD_4__ROWCNT	2
	#define LCD_4__COLCNT	16

	#ifdef _BOOSTC
	  #define LCD_4__DELAY   delay_10us(10)
	#endif
	#ifdef _C2C_
	  #define LCD_4__DELAY   delay_us(100)
	#endif
	#ifdef HI_TECH_C
	  #define LCD_4__DELAY   __delay_us(120)
	#endif
	#ifndef LCD_4__DELAY
	  #define LCD_4__DELAY   delay_us(100)
	#endif




//LCDDisplay(0): //Macro function declarations

void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask);
void FCD_LCDDisplay0_Start();
void FCD_LCDDisplay0_Clear();
void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character);
void FCD_LCDDisplay0_Command(MX_UINT8 in);
void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y);
void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number);
void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String);
void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions);
void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line);
void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7);



//LCDDisplay(0): //Macro implementations


void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask)
{
	
		MX_UINT8 pt;

		FC_CAL_Bit_Low(LCD_4__PORT0, LCD_4__BIT0);
		FC_CAL_Bit_Low(LCD_4__PORT1, LCD_4__BIT1);
		FC_CAL_Bit_Low(LCD_4__PORT2, LCD_4__BIT2);
		FC_CAL_Bit_Low(LCD_4__PORT3, LCD_4__BIT3);
		FC_CAL_Bit_Low(LCD_4__PORT4, LCD_4__RS);
		FC_CAL_Bit_Low(LCD_4__PORT5, LCD_4__E);
		pt = ((in >> 4) & 0x0f);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_4__PORT0, LCD_4__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_4__PORT1, LCD_4__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_4__PORT2, LCD_4__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_4__PORT3, LCD_4__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_4__PORT4, LCD_4__RS);
		LCD_4__DELAY;
		FC_CAL_Bit_High (LCD_4__PORT5, LCD_4__E);
		LCD_4__DELAY;
		FC_CAL_Bit_Low (LCD_4__PORT5, LCD_4__E);
		pt = (in & 0x0f);
		LCD_4__DELAY;
		FC_CAL_Bit_Low(LCD_4__PORT0, LCD_4__BIT0);
		FC_CAL_Bit_Low(LCD_4__PORT1, LCD_4__BIT1);
		FC_CAL_Bit_Low(LCD_4__PORT2, LCD_4__BIT2);
		FC_CAL_Bit_Low(LCD_4__PORT3, LCD_4__BIT3);
		FC_CAL_Bit_Low(LCD_4__PORT4, LCD_4__RS);
		FC_CAL_Bit_Low(LCD_4__PORT5, LCD_4__E);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_4__PORT0, LCD_4__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_4__PORT1, LCD_4__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_4__PORT2, LCD_4__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_4__PORT3, LCD_4__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_4__PORT4, LCD_4__RS);
		LCD_4__DELAY;
		FC_CAL_Bit_High (LCD_4__PORT5, LCD_4__E);
		LCD_4__DELAY;
		FC_CAL_Bit_Low (LCD_4__PORT5, LCD_4__E);
		LCD_4__DELAY;

}

void FCD_LCDDisplay0_Start()
{
	
		FC_CAL_Bit_Low_DDR(LCD_4__PORT0, LCD_4__TRIS0, LCD_4__BIT0);
		FC_CAL_Bit_Low_DDR(LCD_4__PORT1, LCD_4__TRIS1, LCD_4__BIT1);
		FC_CAL_Bit_Low_DDR(LCD_4__PORT2, LCD_4__TRIS2, LCD_4__BIT2);
		FC_CAL_Bit_Low_DDR(LCD_4__PORT3, LCD_4__TRIS3, LCD_4__BIT3);
		FC_CAL_Bit_Low_DDR(LCD_4__PORT4, LCD_4__TRIS4, LCD_4__RS);
		FC_CAL_Bit_Low_DDR(LCD_4__PORT5, LCD_4__TRIS5, LCD_4__E);

		Wdt_Delay_Ms(12);

		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x32, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x2c, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x06, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x0c, 0);
		Wdt_Delay_Ms(2);

		//clear the display
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Clear()
{
	
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character)
{
	
		FCD_LCDDisplay0_RawSend(Character, 0x10);

}

void FCD_LCDDisplay0_Command(MX_UINT8 in)
{
	
		FCD_LCDDisplay0_RawSend(in, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y)
{
	
	  #if (LCD_4__ROWCNT == 1)
	    y=0x80;
	  #endif

	  #if (LCD_4__ROWCNT == 2)
		if (y==0)
			y=0x80;
		else
			y=0xc0;
	  #endif

	  #if (LCD_4__ROWCNT == 4)
		if (y==0)
			y=0x80;
		else if (y==1)
			y=0xc0;

		#if (LCD_4__COLCNT == 16)
			else if (y==2)
				y=0x90;
			else
				y=0xd0;
		#endif

		#if (LCD_4__COLCNT == 20)
			else if (y==2)
				y=0x94;
			else
				y=0xd4;
		#endif
	  #endif

		FCD_LCDDisplay0_RawSend(y+x, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number)
{
	
		MX_SINT16 tmp_int;
		MX_UINT8 tmp_byte;

		if (Number < 0)
		{
			FCD_LCDDisplay0_RawSend('-', 0x10);
			Number = 0 - Number;
		}

		tmp_int = Number;
		if (Number >= 10000)
		{
			tmp_byte = tmp_int / 10000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10000;
				tmp_byte--;
			}
		}
		if (Number >= 1000)
		{
			tmp_byte = tmp_int / 1000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 1000;
				tmp_byte--;
			}
		}
		if (Number >= 100)
		{
			tmp_byte = tmp_int / 100;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 100;
				tmp_byte--;
			}
		}
		if (Number >= 10)
		{
			tmp_byte = tmp_int / 10;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10;
				tmp_byte--;
			}
		}
		FCD_LCDDisplay0_RawSend('0' + tmp_int, 0x10);

}

void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String)
{
	
		MX_UINT8 idx = 0;

		for (idx=0; idx<MSZ_String; idx++)
		{
			if (String[idx] == 0)
			{
				break;
			}
			FCD_LCDDisplay0_RawSend(String[idx], 0x10);
		}

}

void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions)
{
	
		MX_UINT8 cmd = 0;
		MX_UINT8 count;

		//Choose the direction
		switch (Direction)
		{
			case 0:
			case 'l':
			case 'L':

				cmd = 0x18;
				break;

			case 1:
			case 'r':
			case 'R':

				cmd = 0x1C;
				break;

			default:
				break;
		}

		//If direction accepted then scroll the specified amount
		if (cmd)
		{
			for (count = 0; count < Num_Positions; count++)
				FCD_LCDDisplay0_Command(cmd);
		}

}

void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line)
{
	
		MX_UINT8 count;
		MX_UINT8 rowcount;

		//Define number of columns per line
		#if (LCD_4__ROWCNT == 1)
			rowcount=80;
		#endif

		#if (LCD_4__ROWCNT == 2)
			rowcount=40;
		#endif

		#if (LCD_4__ROWCNT == 4)
			#if (LCD_4__COLCNT == 16)
				rowcount=16;
			#endif
			#if (LCD_4__COLCNT == 20)
				rowcount=20;
			#endif
		#endif

		//Start at beginning of the line
		FCD_LCDDisplay0_Cursor (0, Line);

		//Send out spaces to clear line
		for (count = 0; count < rowcount; count++)
			FCD_LCDDisplay0_RawSend(' ', 0x10);

		//Move back to the beginning of the line.
		FCD_LCDDisplay0_Cursor (0, Line);

}

void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7)
{
	   //set CGRAM address

	   FCD_LCDDisplay0_RawSend(64 + (nIdx << 3), 0);
	   delay_ms(2);

	   //write CGRAM data
	   FCD_LCDDisplay0_RawSend(d0, 0x10);
	   FCD_LCDDisplay0_RawSend(d1, 0x10);
	   FCD_LCDDisplay0_RawSend(d2, 0x10);
	   FCD_LCDDisplay0_RawSend(d3, 0x10);
	   FCD_LCDDisplay0_RawSend(d4, 0x10);
	   FCD_LCDDisplay0_RawSend(d5, 0x10);
	   FCD_LCDDisplay0_RawSend(d6, 0x10);
	   FCD_LCDDisplay0_RawSend(d7, 0x10);

	   //Clear the display
	   FCD_LCDDisplay0_RawSend(0x01, 0);
	   delay_ms(2);
	   FCD_LCDDisplay0_RawSend(0x02, 0);
	   delay_ms(2);

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_E()
{

	//Output
	//Output: 1 -> D0
	trisd = trisd & 0xFE;
	if ((1))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 5000 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(155);

	//Output
	//Output: 0 -> D0
	trisd = trisd & 0xFE;
	if ((0))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 5000 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(155);

}


void FCM_E2()
{

	//Output
	//Output: 1 -> D0
	trisd = trisd & 0xFE;
	if ((1))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 4400 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(65);

	//Output
	//Output: 0 -> D0
	trisd = trisd & 0xFE;
	if ((0))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 4400 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(65);

}


void FCM_E3()
{

	//Output
	//Output: 1 -> D0
	trisd = trisd & 0xFE;
	if ((1))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 3900 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(75);

	//Output
	//Output: 0 -> D0
	trisd = trisd & 0xFE;
	if ((0))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 3900 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(75);

}


void FCM_E4()
{

	//Output
	//Output: 1 -> D0
	trisd = trisd & 0xFE;
	if ((1))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 3700 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(130);

	//Output
	//Output: 0 -> D0
	trisd = trisd & 0xFE;
	if ((0))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 3700 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(130);

}


void FCM_E5()
{

	//Output
	//Output: 1 -> D0
	trisd = trisd & 0xFE;
	if ((1))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 3290 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(230);

	//Output
	//Output: 0 -> D0
	trisd = trisd & 0xFE;
	if ((0))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 3290 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(230);

}


void FCM_E6()
{

	//Output
	//Output: 1 -> D0
	trisd = trisd & 0xFE;
	if ((1))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 2900 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(95);

	//Output
	//Output: 0 -> D0
	trisd = trisd & 0xFE;
	if ((0))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 2900 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(95);

}


void FCM_E7()
{

	//Output
	//Output: 1 -> D0
	trisd = trisd & 0xFE;
	if ((1))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 2600 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(50);

	//Output
	//Output: 0 -> D0
	trisd = trisd & 0xFE;
	if ((0))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 2600 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(50);

}


void FCM_E8()
{

	//Output
	//Output: 1 -> D0
	trisd = trisd & 0xFE;
	if ((1))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 2450 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(155);

	//Output
	//Output: 0 -> D0
	trisd = trisd & 0xFE;
	if ((0))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 2450 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(155);

}


void FCM_F()
{

	//Output
	//Output: 1 -> D1
	trisd = trisd & 0xFD;
	if ((1))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 2450 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(155);

	//Output
	//Output: 0 -> D1
	trisd = trisd & 0xFD;
	if ((0))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 2450 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(155);

}


void FCM_F2()
{

	//Output
	//Output: 1 -> D1
	trisd = trisd & 0xFD;
	if ((1))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 2200 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(160);

	//Output
	//Output: 0 -> D1
	trisd = trisd & 0xFD;
	if ((0))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 2200 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(160);

}


void FCM_F3()
{

	//Output
	//Output: 1 -> D1
	trisd = trisd & 0xFD;
	if ((1))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1950 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(165);

	//Output
	//Output: 0 -> D1
	trisd = trisd & 0xFD;
	if ((0))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1950 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(165);

}


void FCM_F5()
{

	//Output
	//Output: 1 -> D1
	trisd = trisd & 0xFD;
	if ((1))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1645 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(115);

	//Output
	//Output: 0 -> D1
	trisd = trisd & 0xFD;
	if ((0))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1645 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(115);

}


void FCM_F6()
{

	//Output
	//Output: 1 -> D1
	trisd = trisd & 0xFD;
	if ((1))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1450 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(175);

	//Output
	//Output: 0 -> D1
	trisd = trisd & 0xFD;
	if ((0))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1450 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(175);

}


void FCM_F7()
{

	//Output
	//Output: 1 -> D1
	trisd = trisd & 0xFD;
	if ((1))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1300 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(25);

	//Output
	//Output: 0 -> D1
	trisd = trisd & 0xFD;
	if ((0))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1300 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(25);

}


void FCM_F8()
{

	//Output
	//Output: 1 -> D1
	trisd = trisd & 0xFD;
	if ((1))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1225 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(205);

	//Output
	//Output: 0 -> D1
	trisd = trisd & 0xFD;
	if ((0))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1225 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(205);

}


void FCM_F4()
{

	//Output
	//Output: 1 -> D1
	trisd = trisd & 0xFD;
	if ((1))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1850 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(65);

	//Output
	//Output: 0 -> D1
	trisd = trisd & 0xFD;
	if ((0))
		portd = (portd & 0xFD) | 0x02;
	else
		portd = portd & 0xFD;

	//Delay
	//Delay: 1850 us
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(255);
	delay_us(65);

}


void FCM_Input_Switches()
{

	//Input
	//Input: B0 -> sw1
	trisb = trisb | 0x01;
	FCV_SW1 = ((portb & 0x01) == 0x01);

	//Input
	//Input: B1 -> sw2
	trisb = trisb | 0x02;
	FCV_SW2 = ((portb & 0x02) == 0x02);

	//Input
	//Input: B2 -> sw3
	trisb = trisb | 0x04;
	FCV_SW3 = ((portb & 0x04) == 0x04);

	//Input
	//Input: B3 -> sw4
	trisb = trisb | 0x08;
	FCV_SW4 = ((portb & 0x08) == 0x08);

	//Input
	//Input: B4 -> sw5
	trisb = trisb | 0x10;
	FCV_SW5 = ((portb & 0x10) == 0x10);

	//Input
	//Input: B5 -> sw6
	trisb = trisb | 0x20;
	FCV_SW6 = ((portb & 0x20) == 0x20);

	//Input
	//Input: B6 -> sw7
	trisb = trisb | 0x40;
	FCV_SW7 = ((portb & 0x40) == 0x40);

	//Input
	//Input: B7 -> sw8
	trisb = trisb | 0x80;
	FCV_SW8 = ((portb & 0x80) == 0x80);

	//Input
	//Input: C0 -> tsw1
	trisc = trisc | 0x01;
	FCV_TSW1 = ((portc & 0x01) == 0x01);

	//Input
	//Input: C1 -> tsw2
	trisc = trisc | 0x02;
	FCV_TSW2 = ((portc & 0x02) == 0x02);

	//Input
	//Input: C2 -> tsw3
	trisc = trisc | 0x04;
	FCV_TSW3 = ((portc & 0x04) == 0x04);

	//Input
	//Input: C3 -> tsw4
	trisc = trisc | 0x08;
	FCV_TSW4 = ((portc & 0x08) == 0x08);

	//Input
	//Input: C4 -> tsw5
	trisc = trisc | 0x10;
	FCV_TSW5 = ((portc & 0x10) == 0x10);

	//Input
	//Input: C5 -> tsw6
	trisc = trisc | 0x20;
	FCV_TSW6 = ((portc & 0x20) == 0x20);

	//Input
	//Input: C6 -> tsw7
	trisc = trisc | 0x40;
	FCV_TSW7 = ((portc & 0x40) == 0x40);

	//Input
	//Input: C7 -> tsw8
	trisc = trisc | 0x80;
	FCV_TSW8 = ((portc & 0x80) == 0x80);

	//Input
	//Input: E0 -> play
	trise = trise | 0x01;
	FCV_PLAY = ((porte & 0x01) == 0x01);

	//Input
	//Input: E1 -> demo
	trise = trise | 0x02;
	FCV_DEMO = ((porte & 0x02) == 0x02);

	//Input
	//Input: E2 -> SFX
	trise = trise | 0x04;
	FCV_SFX = ((porte & 0x04) == 0x04);

}


void FCM_Octave1()
{

	//Decision
	//Decision: sw1 = 1?
	if (FCV_SW1 == 1)
	{

		//Call Macro
		//Call Macro: E()
		FCM_E();

	// } else {

	}

	//Decision
	//Decision: sw2 = 1?
	if (FCV_SW2 == 1)
	{

		//Call Macro
		//Call Macro: E2()
		FCM_E2();

	// } else {

	}

	//Decision
	//Decision: sw3 = 1?
	if (FCV_SW3 == 1)
	{

		//Call Macro
		//Call Macro: E3()
		FCM_E3();

	// } else {

	}

	//Decision
	//Decision: sw4 = 1?
	if (FCV_SW4 == 1)
	{

		//Call Macro
		//Call Macro: E4()
		FCM_E4();

	// } else {

	}

	//Decision
	//Decision: sw5 = 1?
	if (FCV_SW5 == 1)
	{

		//Call Macro
		//Call Macro: E5()
		FCM_E5();

	// } else {

	}

	//Decision
	//Decision: sw6 = 1?
	if (FCV_SW6 == 1)
	{

		//Call Macro
		//Call Macro: E6()
		FCM_E6();

	// } else {

	}

	//Decision
	//Decision: sw7 = 1?
	if (FCV_SW7 == 1)
	{

		//Call Macro
		//Call Macro: E7()
		FCM_E7();

	// } else {

	}

	//Decision
	//Decision: sw8 = 1?
	if (FCV_SW8 == 1)
	{

		//Call Macro
		//Call Macro: E8()
		FCM_E8();

	// } else {

	}

}


void FCM_Octave2()
{

	//Decision
	//Decision: tsw1 = 1?
	if (FCV_TSW1 == 1)
	{

		//Call Macro
		//Call Macro: F()
		FCM_F();

	// } else {

	}

	//Decision
	//Decision: tsw2 = 1?
	if (FCV_TSW2 == 1)
	{

		//Call Macro
		//Call Macro: F2()
		FCM_F2();

	// } else {

	}

	//Decision
	//Decision: tsw3 = 1?
	if (FCV_TSW3 == 1)
	{

		//Call Macro
		//Call Macro: F3()
		FCM_F3();

	// } else {

	}

	//Decision
	//Decision: tsw4 = 1?
	if (FCV_TSW4 == 1)
	{

		//Call Macro
		//Call Macro: F4()
		FCM_F4();

	// } else {

	}

	//Decision
	//Decision: tsw5 = 1?
	if (FCV_TSW5 == 1)
	{

		//Call Macro
		//Call Macro: F5()
		FCM_F5();

	// } else {

	}

	//Decision
	//Decision: tsw6 = 1?
	if (FCV_TSW6 == 1)
	{

		//Call Macro
		//Call Macro: F6()
		FCM_F6();

	// } else {

	}

	//Decision
	//Decision: tsw7 = 1?
	if (FCV_TSW7 == 1)
	{

		//Call Macro
		//Call Macro: F7()
		FCM_F7();

	// } else {

	}

	//Decision
	//Decision: tsw8 = 1?
	if (FCV_TSW8 == 1)
	{

		//Call Macro
		//Call Macro: F8()
		FCM_F8();

	// } else {

	}

}


void FCM_quarter()
{

	//Output
	//Output: 1 -> D0
	trisd = trisd & 0xFE;
	if ((1))
		portd = (portd & 0xFE) | 0x01;
	else
		portd = portd & 0xFE;

	//Delay
	//Delay: 500 ms
	delay_ms(255);
	delay_ms(245);

}


void FCM_MiSi()
{

	//loop
	//Loop: Loop 5 times
	for (FCLV_LOOP1=0; FCLV_LOOP1<5; FCLV_LOOP1++)
	{

		//Call Macro
		//Call Macro: E3()
		FCM_E3();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 20 times
	for (FCLV_LOOP2=0; FCLV_LOOP2<20; FCLV_LOOP2++)
	{

		//Call Macro
		//Call Macro: F7()
		FCM_F7();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

}


void FCM_MiFaReRe()
{

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP3=0; FCLV_LOOP3<10; FCLV_LOOP3++)
	{

		//Call Macro
		//Call Macro: E3()
		FCM_E3();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP4=0; FCLV_LOOP4<10; FCLV_LOOP4++)
	{

		//Call Macro
		//Call Macro: E4()
		FCM_E4();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP5=0; FCLV_LOOP5<10; FCLV_LOOP5++)
	{

		//Call Macro
		//Call Macro: E2()
		FCM_E2();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP6=0; FCLV_LOOP6<10; FCLV_LOOP6++)
	{

		//Call Macro
		//Call Macro: E2()
		FCM_E2();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP7=0; FCLV_LOOP7<10; FCLV_LOOP7++)
	{

		//Call Macro
		//Call Macro: E3()
		FCM_E3();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

}


void FCM_DoDoDo()
{

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP8=0; FCLV_LOOP8<10; FCLV_LOOP8++)
	{

		//Call Macro
		//Call Macro: E()
		FCM_E();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 15 times
	for (FCLV_LOOP9=0; FCLV_LOOP9<15; FCLV_LOOP9++)
	{

		//Call Macro
		//Call Macro: F7()
		FCM_F7();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//DoDo2
	//Call Macro: DoDo2()
	FCM_DoDo2();

	//loop
	//Loop: Loop 15 times
	for (FCLV_LOOP10=0; FCLV_LOOP10<15; FCLV_LOOP10++)
	{

		//Call Macro
		//Call Macro: F8()
		FCM_F8();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//DoDo2
	//Call Macro: DoDo2()
	FCM_DoDo2();

	//loop
	//Loop: Loop 15 times
	for (FCLV_LOOP11=0; FCLV_LOOP11<15; FCLV_LOOP11++)
	{

		//Call Macro
		//Call Macro: F6()
		FCM_F6();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//DoDo2
	//Call Macro: DoDo2()
	FCM_DoDo2();

	//loop
	//Loop: Loop 15 times
	for (FCLV_LOOP12=0; FCLV_LOOP12<15; FCLV_LOOP12++)
	{

		//Call Macro
		//Call Macro: F7()
		FCM_F7();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//DoDo2
	//Call Macro: DoDo2()
	FCM_DoDo2();

	//loop
	//Loop: Loop 15 times
	for (FCLV_LOOP13=0; FCLV_LOOP13<15; FCLV_LOOP13++)
	{

		//Call Macro
		//Call Macro: F5()
		FCM_F5();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//DoDo2
	//Call Macro: DoDo2()
	FCM_DoDo2();

	//loop
	//Loop: Loop 15 times
	for (FCLV_LOOP14=0; FCLV_LOOP14<15; FCLV_LOOP14++)
	{

		//Call Macro
		//Call Macro: F6()
		FCM_F6();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//DoDo2
	//Call Macro: DoDo2()
	FCM_DoDo2();

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP15=0; FCLV_LOOP15<10; FCLV_LOOP15++)
	{

		//Call Macro
		//Call Macro: F4()
		FCM_F4();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP16=0; FCLV_LOOP16<10; FCLV_LOOP16++)
	{

		//Call Macro
		//Call Macro: E()
		FCM_E();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP17=0; FCLV_LOOP17<10; FCLV_LOOP17++)
	{

		//Call Macro
		//Call Macro: F4()
		FCM_F4();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP18=0; FCLV_LOOP18<10; FCLV_LOOP18++)
	{

		//Call Macro
		//Call Macro: E()
		FCM_E();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

}


void FCM_DoDo2()
{

	//loop
	//Loop: Loop 7 times
	for (FCLV_LOOP19=0; FCLV_LOOP19<7; FCLV_LOOP19++)
	{

		//Call Macro
		//Call Macro: E()
		FCM_E();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 7 times
	for (FCLV_LOOP20=0; FCLV_LOOP20<7; FCLV_LOOP20++)
	{

		//Call Macro
		//Call Macro: E()
		FCM_E();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

}


void FCM_FaDoTrans()
{

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP21=0; FCLV_LOOP21<10; FCLV_LOOP21++)
	{

		//Call Macro
		//Call Macro: F4()
		FCM_F4();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//DoDo2
	//Call Macro: DoDo2()
	FCM_DoDo2();

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP22=0; FCLV_LOOP22<10; FCLV_LOOP22++)
	{

		//Call Macro
		//Call Macro: F4()
		FCM_F4();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//DoDo2
	//Call Macro: DoDo2()
	FCM_DoDo2();

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP23=0; FCLV_LOOP23<10; FCLV_LOOP23++)
	{

		//Call Macro
		//Call Macro: F4()
		FCM_F4();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

	//loop
	//Loop: Loop 10 times
	for (FCLV_LOOP24=0; FCLV_LOOP24<10; FCLV_LOOP24++)
	{

		//Call Macro
		//Call Macro: E()
		FCM_E();


	}

	//Delay
	//Delay: 80 ms
	delay_ms(80);

}


void FCM_intro()
{

	//Loop
	//Loop: Loop 3 times
	for (FCLV_LOOP25=0; FCLV_LOOP25<3; FCLV_LOOP25++)
	{

		//loop
		//Loop: Loop 4 times
		for (FCLV_LOOP26=0; FCLV_LOOP26<4; FCLV_LOOP26++)
		{

			//loop
			//Loop: Loop 10 times
			for (FCLV_LOOP27=0; FCLV_LOOP27<10; FCLV_LOOP27++)
			{

				//Call Macro
				//Call Macro: E3()
				FCM_E3();


			}

			//Delay
			//Delay: 80 ms
			delay_ms(80);


		}

		//Delay
		//Delay: 650 ms
		delay_ms(255);
		delay_ms(255);
		delay_ms(140);


	}

}


void FCM_DEMO()
{

	//intro
	//Call Macro: intro()
	FCM_intro();

	//Input
	//Input: E1 -> demo
	trise = trise | 0x02;
	FCV_DEMO = ((porte & 0x02) == 0x02);

	//Decision
	//Decision: demo != 1?
	if (FCV_DEMO != 1)
	{

		//Goto Connection Point
		//Goto Connection Point: [A]: A
		goto FCC_DEMO_A;

	// } else {

	}

	//Call Macro
	//Call Macro: MiSi()
	FCM_MiSi();

	//Input
	//Input: E1 -> demo
	trise = trise | 0x02;
	FCV_DEMO = ((porte & 0x02) == 0x02);

	//Decision
	//Decision: demo != 1?
	if (FCV_DEMO != 1)
	{

		//Goto Connection Point
		//Goto Connection Point: [A]: A
		goto FCC_DEMO_A;

	// } else {

	}

	//loop
	//Loop: Loop 11 times
	for (FCLV_LOOP28=0; FCLV_LOOP28<11; FCLV_LOOP28++)
	{

		//loop
		//Loop: Loop 10 times
		for (FCLV_LOOP29=0; FCLV_LOOP29<10; FCLV_LOOP29++)
		{

			//Input
			//Input: E1 -> demo
			trise = trise | 0x02;
			FCV_DEMO = ((porte & 0x02) == 0x02);

			//Decision
			//Decision: demo != 1?
			if (FCV_DEMO != 1)
			{

				//Goto Connection Point
				//Goto Connection Point: [A]: A
				goto FCC_DEMO_A;

			// } else {

			}

			//Call Macro
			//Call Macro: E3()
			FCM_E3();


		}

		//Delay
		//Delay: 80 ms
		delay_ms(80);


	}

	//MiFaReRe
	//Call Macro: MiFaReRe()
	FCM_MiFaReRe();

	//Input
	//Input: E1 -> demo
	trise = trise | 0x02;
	FCV_DEMO = ((porte & 0x02) == 0x02);

	//Decision
	//Decision: demo != 1?
	if (FCV_DEMO != 1)
	{

		//Goto Connection Point
		//Goto Connection Point: [A]: A
		goto FCC_DEMO_A;

	// } else {

	}

	//Call Macro
	//Call Macro: MiSi()
	FCM_MiSi();

	//Input
	//Input: E1 -> demo
	trise = trise | 0x02;
	FCV_DEMO = ((porte & 0x02) == 0x02);

	//Decision
	//Decision: demo != 1?
	if (FCV_DEMO != 1)
	{

		//Goto Connection Point
		//Goto Connection Point: [A]: A
		goto FCC_DEMO_A;

	// } else {

	}

	//loop
	//Loop: Loop 9 times
	for (FCLV_LOOP30=0; FCLV_LOOP30<9; FCLV_LOOP30++)
	{

		//loop
		//Loop: Loop 10 times
		for (FCLV_LOOP31=0; FCLV_LOOP31<10; FCLV_LOOP31++)
		{

			//Input
			//Input: E1 -> demo
			trise = trise | 0x02;
			FCV_DEMO = ((porte & 0x02) == 0x02);

			//Decision
			//Decision: demo != 1?
			if (FCV_DEMO != 1)
			{

				//Goto Connection Point
				//Goto Connection Point: [A]: A
				goto FCC_DEMO_A;

			// } else {

			}

			//Call Macro
			//Call Macro: E3()
			FCM_E3();


		}

		//Delay
		//Delay: 80 ms
		delay_ms(80);


	}

	//MiFaReRe
	//Call Macro: MiFaReRe()
	FCM_MiFaReRe();

	//Input
	//Input: E1 -> demo
	trise = trise | 0x02;
	FCV_DEMO = ((porte & 0x02) == 0x02);

	//Decision
	//Decision: demo != 1?
	if (FCV_DEMO != 1)
	{

		//Goto Connection Point
		//Goto Connection Point: [A]: A
		goto FCC_DEMO_A;

	// } else {

	}

	//Loop
	//Loop: Loop 2 times
	for (FCLV_LOOP32=0; FCLV_LOOP32<2; FCLV_LOOP32++)
	{

		//Call Macro
		//Call Macro: DoDoDo()
		FCM_DoDoDo();

		//Input
		//Input: E1 -> demo
		trise = trise | 0x02;
		FCV_DEMO = ((porte & 0x02) == 0x02);

		//Decision
		//Decision: demo != 1?
		if (FCV_DEMO != 1)
		{

			//Goto Connection Point
			//Goto Connection Point: [A]: A
			goto FCC_DEMO_A;

		// } else {

		}


	}

	//FaDoTrans
	//Call Macro: FaDoTrans()
	FCM_FaDoTrans();

	//Connection Point
	//Connection Point: [A]: A
FCC_DEMO_A:
;

}


void FCM_SFX()
{

	//Decision
	//Decision: sw1 = 1?
	if (FCV_SW1 == 1)
	{

		//Output
		//Output: 3 -> PORTD
		trisd = 0x00;
		portd = (3);

		//Delay
		//Delay: delay us
		delay_us(FCV_DELAY);

		//Output
		//Output: 0 -> PORTD
		trisd = 0x00;
		portd = (0);

		//Delay
		//Delay: delay us
		delay_us(FCV_DELAY);

		//Calculation
		//Calculation:
		//  delay = delay - 1
		FCV_DELAY = FCV_DELAY - 1;

	// } else {

	}

	//Decision
	//Decision: sw2 = 1?
	if (FCV_SW2 == 1)
	{

		//Output
		//Output: 3 -> PORTD
		trisd = 0x00;
		portd = (3);

		//Delay
		//Delay: delay us
		delay_us(FCV_DELAY);

		//Output
		//Output: 0 -> PORTD
		trisd = 0x00;
		portd = (0);

		//Delay
		//Delay: delay us
		delay_us(FCV_DELAY);

		//Calculation
		//Calculation:
		//  delay = delay + 2.5
		FCV_DELAY = flt_toi(flt_add(flt_fromi(FCV_DELAY), 2.5));

	// } else {

	}

	//Decision
	//Decision: sw3 = 1?
	if (FCV_SW3 == 1)
	{

		//Output
		//Output: 3 -> PORTD
		trisd = 0x00;
		portd = (3);

		//Delay
		//Delay: delay us
		delay_us(FCV_DELAY);

		//Output
		//Output: 0 -> PORTD
		trisd = 0x00;
		portd = (0);

		//Delay
		//Delay: delay us
		delay_us(FCV_DELAY);

		//Calculation
		//Calculation:
		//  delay = delay + 3
		FCV_DELAY = FCV_DELAY + 3;

	// } else {

	}

	//Decision
	//Decision: sw4 = 1?
	if (FCV_SW4 == 1)
	{

		//Output
		//Output: 3 -> PORTD
		trisd = 0x00;
		portd = (3);

		//Delay
		//Delay: 1000 us
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(235);

		//Output
		//Output: 0 -> PORTD
		trisd = 0x00;
		portd = (0);

		//Delay
		//Delay: 1000 us
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(235);

	// } else {

	}

	//Decision
	//Decision: sw5 = 1?
	if (FCV_SW5 == 1)
	{

		//Output
		//Output: 3 -> PORTD
		trisd = 0x00;
		portd = (3);

		//Delay
		//Delay: 7500 us
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(105);

		//Output
		//Output: 0 -> PORTD
		trisd = 0x00;
		portd = (0);

		//Delay
		//Delay: 7500 us
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(105);

	// } else {

	}

	//Decision
	//Decision: sw6 = 1?
	if (FCV_SW6 == 1)
	{

		//Output
		//Output: 3 -> PORTD
		trisd = 0x00;
		portd = (3);

		//Delay
		//Delay: 5000 us
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(155);

		//Output
		//Output: 0 -> PORTD
		trisd = 0x00;
		portd = (0);

		//Delay
		//Delay: 5000 us
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(255);
		delay_us(155);

	// } else {

	}

	//Decision
	//Decision: sw7 = 1?
	if (FCV_SW7 == 1)
	{

		//Output
		//Output: 3 -> PORTD
		trisd = 0x00;
		portd = (3);

		//Delay
		//Delay: 500 us
		delay_us(255);
		delay_us(245);

		//Output
		//Output: 0 -> PORTD
		trisd = 0x00;
		portd = (0);

		//Delay
		//Delay: 500 us
		delay_us(255);
		delay_us(245);

	// } else {

	}

	//Decision
	//Decision: sw8 = 1?
	if (FCV_SW8 == 1)
	{

		//Output
		//Output: 3 -> PORTD
		trisd = 0x00;
		portd = (3);

		//Delay
		//Delay: 250 us
		delay_us(250);

		//Output
		//Output: 0 -> PORTD
		trisd = 0x00;
		portd = (0);

		//Delay
		//Delay: 250 us
		delay_us(250);

	// } else {

	}

}


void FCM_PLAY()
{

	//Note_generator
	//Call Macro: Octave1()
	FCM_Octave1();

	//Note_generator
	//Call Macro: Octave2()
	FCM_Octave2();

}


void FCM_LCD()
{

	//Call Component Macro
	//Call Component Macro: ClearLine(1)
	FCD_LCDDisplay0_ClearLine(1);

	//Decision
	//Decision: play = 1?
	if (FCV_PLAY == 1)
	{

		//Call Component Macro
		//Call Component Macro: ClearLine(1)
		FCD_LCDDisplay0_ClearLine(1);

		//Call Component Macro
		//Call Component Macro: Cursor(0, 1)
		FCD_LCDDisplay0_Cursor(0, 1);

		//Call Component Macro
		//Call Component Macro: PrintASCII("Play Mode")
		FCD_LCDDisplay0_PrintASCII('P');
		FCD_LCDDisplay0_PrintASCII('l');
		FCD_LCDDisplay0_PrintASCII('a');
		FCD_LCDDisplay0_PrintASCII('y');
		FCD_LCDDisplay0_PrintASCII(' ');
		FCD_LCDDisplay0_PrintASCII('M');
		FCD_LCDDisplay0_PrintASCII('o');
		FCD_LCDDisplay0_PrintASCII('d');
		FCD_LCDDisplay0_PrintASCII('e');

	} else {

		//Decision
		//Decision: SFX = 1?
		if (FCV_SFX == 1)
		{

			//Call Component Macro
			//Call Component Macro: ClearLine(1)
			FCD_LCDDisplay0_ClearLine(1);

			//Call Component Macro
			//Call Component Macro: Cursor(0, 1)
			FCD_LCDDisplay0_Cursor(0, 1);

			//Call Component Macro
			//Call Component Macro: PrintASCII("SFX Mode")
			FCD_LCDDisplay0_PrintASCII('S');
			FCD_LCDDisplay0_PrintASCII('F');
			FCD_LCDDisplay0_PrintASCII('X');
			FCD_LCDDisplay0_PrintASCII(' ');
			FCD_LCDDisplay0_PrintASCII('M');
			FCD_LCDDisplay0_PrintASCII('o');
			FCD_LCDDisplay0_PrintASCII('d');
			FCD_LCDDisplay0_PrintASCII('e');

		} else {

			//Decision
			//Decision: demo = 1?
			if (FCV_DEMO == 1)
			{

				//Call Component Macro
				//Call Component Macro: ClearLine(1)
				FCD_LCDDisplay0_ClearLine(1);

				//Call Component Macro
				//Call Component Macro: Cursor(0, 1)
				FCD_LCDDisplay0_Cursor(0, 1);

				//Call Component Macro
				//Call Component Macro: PrintASCII("Demo Mode")
				FCD_LCDDisplay0_PrintASCII('D');
				FCD_LCDDisplay0_PrintASCII('e');
				FCD_LCDDisplay0_PrintASCII('m');
				FCD_LCDDisplay0_PrintASCII('o');
				FCD_LCDDisplay0_PrintASCII(' ');
				FCD_LCDDisplay0_PrintASCII('M');
				FCD_LCDDisplay0_PrintASCII('o');
				FCD_LCDDisplay0_PrintASCII('d');
				FCD_LCDDisplay0_PrintASCII('e');

			// } else {

			}

		}

	}

}



void main()
{
	//Initialization
	adcon1 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//calculation
	//Calculation:
	//  delay = 7500
	//  demo = 0
	//  play = 0
	//  SFX = 0
	FCV_DELAY = 7500;
	FCV_DEMO = 0;
	FCV_PLAY = 0;
	FCV_SFX = 0;

	//Loop
	//Loop: While 1
	while (1)
	{

		//Inputs_Declare
		//Call Macro: Input_Switches()
		FCM_Input_Switches();

		//Output
		//Output: 0 -> PORTB
		trisb = 0x00;
		portb = (0);

		//Output
		//Output: 0 -> PORTC
		trisc = 0x00;
		portc = (0);

		//Output
		//Output: 0 -> PORTD
		trisd = 0x00;
		portd = (0);

		//Decision
		//Decision: play = 1?
		if (FCV_PLAY == 1)
		{

			//Decision
			//Decision: SFX = 1?
			if (FCV_SFX == 1)
			{

			} else {

				//Decision
				//Decision: demo = 1?
				if (FCV_DEMO == 1)
				{

				} else {

					//Call Macro
					//Call Macro: PLAY()
					FCM_PLAY();

				}

			}

		// } else {

		}

		//Decision
		//Decision: demo = 1?
		if (FCV_DEMO == 1)
		{

			//Decision
			//Decision: play = 1?
			if (FCV_PLAY == 1)
			{

			} else {

				//Decision
				//Decision: SFX = 1?
				if (FCV_SFX == 1)
				{

				} else {

					//DEMO
					//Call Macro: DEMO()
					FCM_DEMO();

				}

			}

		// } else {

		}

		//Decision
		//Decision: SFX = 1?
		if (FCV_SFX == 1)
		{

			//Decision
			//Decision: demo = 1?
			if (FCV_DEMO == 1)
			{

			} else {

				//Decision
				//Decision: play = 1?
				if (FCV_PLAY == 1)
				{

				} else {

					//SFX
					//Call Macro: SFX()
					FCM_SFX();

				}

			}

		// } else {

		}


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



