//************************************************************************************
//**  
//**  File name:     G:\group_proj\pic2_finalRev.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Wednesday, August 13, 2014 13:41:25
//**  Licence:       50 User
//**  Registered to: BCITETCC2012
//**  Licence key:   91DZ5U
//**  
//**  
//**     NOT FOR COMMERCIAL USE
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F877
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_30
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 19660800
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f7a
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f7a);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations


//Variable declarations
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_UINT8 FCV_DEMO;
MX_UINT8 FCV_PLAY;
MX_UINT8 FCV_SEL;
MX_UINT8 FCV_SFX;

MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;
MX_UINT8 FCLV_LOOP4;



//LCDDisplay(0): //Defines:

/**** Macro Substitutions ****
a = Unique Component Reference Number
b = D1 Port Letter
c = D2 Port Letter
d = D3 Port Letter
e = D4 Port Letter
f = RS Port Letter
g = E Port Letter
h = Data 1_Pin
i = Data 2 Pin
j = Data 3 Pin
k = Data 4 Pin
l = RS Pin
m = Enable Pin
n = Row Count
o = Column Count
******************************/

	//component connections
	//Port pin lat workaround for 8-bit PIC devices running >= 32MHz
	//seems we need this mod for 19660800 16F1937 so changed to >= 16MHz

  #ifdef FC_CAL_PIC
   #if MX_CLK_SPEED >= 32000000
	#define LCD_1__PORT0    latc
	#define LCD_1__PORT1    latc
	#define LCD_1__PORT2    latc
	#define LCD_1__PORT3    latc
	#define LCD_1__PORT4    latc
	#define LCD_1__PORT5    latc
   #else
    #ifdef MX_LCD_PORT_LAT
	 #define LCD_1__PORT0    latc
	 #define LCD_1__PORT1    latc
	 #define LCD_1__PORT2    latc
	 #define LCD_1__PORT3    latc
	 #define LCD_1__PORT4    latc
	 #define LCD_1__PORT5    latc
    #else
	 #define LCD_1__PORT0    portc
	 #define LCD_1__PORT1    portc
	 #define LCD_1__PORT2    portc
	 #define LCD_1__PORT3    portc
	 #define LCD_1__PORT4    portc
	 #define LCD_1__PORT5    portc
	#endif
   #endif
  #else
	#define LCD_1__PORT0    portc
	#define LCD_1__PORT1    portc
	#define LCD_1__PORT2    portc
	#define LCD_1__PORT3    portc
	#define LCD_1__PORT4    portc
	#define LCD_1__PORT5    portc
  #endif

	#define LCD_1__TRIS0    trisc
	#define LCD_1__TRIS1    trisc
	#define LCD_1__TRIS2    trisc
	#define LCD_1__TRIS3    trisc
	#define LCD_1__TRIS4    trisc
	#define LCD_1__TRIS5    trisc
	#define LCD_1__BIT0    	0
	#define LCD_1__BIT1    	1
	#define LCD_1__BIT2    	2
	#define LCD_1__BIT3    	3
	#define LCD_1__RS      	4
	#define LCD_1__E       	5
	#define LCD_1__ROWCNT	2
	#define LCD_1__COLCNT	16

	#ifdef _BOOSTC
	  #define LCD_1__DELAY   delay_10us(10)
	#endif
	#ifdef _C2C_
	  #define LCD_1__DELAY   delay_us(100)
	#endif
	#ifdef HI_TECH_C
	  #define LCD_1__DELAY   __delay_us(120)
	#endif
	#ifndef LCD_1__DELAY
	  #define LCD_1__DELAY   delay_us(100)
	#endif




//LCDDisplay(0): //Macro function declarations

void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask);
void FCD_LCDDisplay0_Start();
void FCD_LCDDisplay0_Clear();
void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character);
void FCD_LCDDisplay0_Command(MX_UINT8 in);
void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y);
void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number);
void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String);
void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions);
void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line);
void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7);



//LCDDisplay(0): //Macro implementations


void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask)
{
	
		MX_UINT8 pt;

		FC_CAL_Bit_Low(LCD_1__PORT0, LCD_1__BIT0);
		FC_CAL_Bit_Low(LCD_1__PORT1, LCD_1__BIT1);
		FC_CAL_Bit_Low(LCD_1__PORT2, LCD_1__BIT2);
		FC_CAL_Bit_Low(LCD_1__PORT3, LCD_1__BIT3);
		FC_CAL_Bit_Low(LCD_1__PORT4, LCD_1__RS);
		FC_CAL_Bit_Low(LCD_1__PORT5, LCD_1__E);
		pt = ((in >> 4) & 0x0f);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_1__PORT0, LCD_1__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_1__PORT1, LCD_1__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_1__PORT2, LCD_1__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_1__PORT3, LCD_1__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_1__PORT4, LCD_1__RS);
		LCD_1__DELAY;
		FC_CAL_Bit_High (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;
		FC_CAL_Bit_Low (LCD_1__PORT5, LCD_1__E);
		pt = (in & 0x0f);
		LCD_1__DELAY;
		FC_CAL_Bit_Low(LCD_1__PORT0, LCD_1__BIT0);
		FC_CAL_Bit_Low(LCD_1__PORT1, LCD_1__BIT1);
		FC_CAL_Bit_Low(LCD_1__PORT2, LCD_1__BIT2);
		FC_CAL_Bit_Low(LCD_1__PORT3, LCD_1__BIT3);
		FC_CAL_Bit_Low(LCD_1__PORT4, LCD_1__RS);
		FC_CAL_Bit_Low(LCD_1__PORT5, LCD_1__E);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_1__PORT0, LCD_1__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_1__PORT1, LCD_1__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_1__PORT2, LCD_1__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_1__PORT3, LCD_1__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_1__PORT4, LCD_1__RS);
		LCD_1__DELAY;
		FC_CAL_Bit_High (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;
		FC_CAL_Bit_Low (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;

}

void FCD_LCDDisplay0_Start()
{
	
		FC_CAL_Bit_Low_DDR(LCD_1__PORT0, LCD_1__TRIS0, LCD_1__BIT0);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT1, LCD_1__TRIS1, LCD_1__BIT1);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT2, LCD_1__TRIS2, LCD_1__BIT2);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT3, LCD_1__TRIS3, LCD_1__BIT3);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT4, LCD_1__TRIS4, LCD_1__RS);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT5, LCD_1__TRIS5, LCD_1__E);

		Wdt_Delay_Ms(12);

		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x32, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x2c, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x06, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x0c, 0);
		Wdt_Delay_Ms(2);

		//clear the display
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Clear()
{
	
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character)
{
	
		FCD_LCDDisplay0_RawSend(Character, 0x10);

}

void FCD_LCDDisplay0_Command(MX_UINT8 in)
{
	
		FCD_LCDDisplay0_RawSend(in, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y)
{
	
	  #if (LCD_1__ROWCNT == 1)
	    y=0x80;
	  #endif

	  #if (LCD_1__ROWCNT == 2)
		if (y==0)
			y=0x80;
		else
			y=0xc0;
	  #endif

	  #if (LCD_1__ROWCNT == 4)
		if (y==0)
			y=0x80;
		else if (y==1)
			y=0xc0;

		#if (LCD_1__COLCNT == 16)
			else if (y==2)
				y=0x90;
			else
				y=0xd0;
		#endif

		#if (LCD_1__COLCNT == 20)
			else if (y==2)
				y=0x94;
			else
				y=0xd4;
		#endif
	  #endif

		FCD_LCDDisplay0_RawSend(y+x, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number)
{
	
		MX_SINT16 tmp_int;
		MX_UINT8 tmp_byte;

		if (Number < 0)
		{
			FCD_LCDDisplay0_RawSend('-', 0x10);
			Number = 0 - Number;
		}

		tmp_int = Number;
		if (Number >= 10000)
		{
			tmp_byte = tmp_int / 10000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10000;
				tmp_byte--;
			}
		}
		if (Number >= 1000)
		{
			tmp_byte = tmp_int / 1000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 1000;
				tmp_byte--;
			}
		}
		if (Number >= 100)
		{
			tmp_byte = tmp_int / 100;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 100;
				tmp_byte--;
			}
		}
		if (Number >= 10)
		{
			tmp_byte = tmp_int / 10;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10;
				tmp_byte--;
			}
		}
		FCD_LCDDisplay0_RawSend('0' + tmp_int, 0x10);

}

void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String)
{
	
		MX_UINT8 idx = 0;

		for (idx=0; idx<MSZ_String; idx++)
		{
			if (String[idx] == 0)
			{
				break;
			}
			FCD_LCDDisplay0_RawSend(String[idx], 0x10);
		}

}

void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions)
{
	
		MX_UINT8 cmd = 0;
		MX_UINT8 count;

		//Choose the direction
		switch (Direction)
		{
			case 0:
			case 'l':
			case 'L':

				cmd = 0x18;
				break;

			case 1:
			case 'r':
			case 'R':

				cmd = 0x1C;
				break;

			default:
				break;
		}

		//If direction accepted then scroll the specified amount
		if (cmd)
		{
			for (count = 0; count < Num_Positions; count++)
				FCD_LCDDisplay0_Command(cmd);
		}

}

void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line)
{
	
		MX_UINT8 count;
		MX_UINT8 rowcount;

		//Define number of columns per line
		#if (LCD_1__ROWCNT == 1)
			rowcount=80;
		#endif

		#if (LCD_1__ROWCNT == 2)
			rowcount=40;
		#endif

		#if (LCD_1__ROWCNT == 4)
			#if (LCD_1__COLCNT == 16)
				rowcount=16;
			#endif
			#if (LCD_1__COLCNT == 20)
				rowcount=20;
			#endif
		#endif

		//Start at beginning of the line
		FCD_LCDDisplay0_Cursor (0, Line);

		//Send out spaces to clear line
		for (count = 0; count < rowcount; count++)
			FCD_LCDDisplay0_RawSend(' ', 0x10);

		//Move back to the beginning of the line.
		FCD_LCDDisplay0_Cursor (0, Line);

}

void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7)
{
	   //set CGRAM address

	   FCD_LCDDisplay0_RawSend(64 + (nIdx << 3), 0);
	   delay_ms(2);

	   //write CGRAM data
	   FCD_LCDDisplay0_RawSend(d0, 0x10);
	   FCD_LCDDisplay0_RawSend(d1, 0x10);
	   FCD_LCDDisplay0_RawSend(d2, 0x10);
	   FCD_LCDDisplay0_RawSend(d3, 0x10);
	   FCD_LCDDisplay0_RawSend(d4, 0x10);
	   FCD_LCDDisplay0_RawSend(d5, 0x10);
	   FCD_LCDDisplay0_RawSend(d6, 0x10);
	   FCD_LCDDisplay0_RawSend(d7, 0x10);

	   //Clear the display
	   FCD_LCDDisplay0_RawSend(0x01, 0);
	   delay_ms(2);
	   FCD_LCDDisplay0_RawSend(0x02, 0);
	   delay_ms(2);

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations



void main()
{
	//Initialization
	adcon1 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Call Component Macro
	//Call Component Macro: Start()
	FCD_LCDDisplay0_Start();

	//Call Component Macro
	//Call Component Macro: Cursor(1, 0)
	FCD_LCDDisplay0_Cursor(1, 0);

	//Call Component Macro
	//Call Component Macro: PrintASCII("Hi, I am IAM1302. Hit my switches")
	FCD_LCDDisplay0_PrintASCII('H');
	FCD_LCDDisplay0_PrintASCII('i');
	FCD_LCDDisplay0_PrintASCII(',');
	FCD_LCDDisplay0_PrintASCII(' ');
	FCD_LCDDisplay0_PrintASCII('I');
	FCD_LCDDisplay0_PrintASCII(' ');
	FCD_LCDDisplay0_PrintASCII('a');
	FCD_LCDDisplay0_PrintASCII('m');
	FCD_LCDDisplay0_PrintASCII(' ');
	FCD_LCDDisplay0_PrintASCII('I');
	FCD_LCDDisplay0_PrintASCII('A');
	FCD_LCDDisplay0_PrintASCII('M');
	FCD_LCDDisplay0_PrintASCII('1');
	FCD_LCDDisplay0_PrintASCII('3');
	FCD_LCDDisplay0_PrintASCII('0');
	FCD_LCDDisplay0_PrintASCII('2');
	FCD_LCDDisplay0_PrintASCII('.');
	FCD_LCDDisplay0_PrintASCII(' ');
	FCD_LCDDisplay0_PrintASCII('H');
	FCD_LCDDisplay0_PrintASCII('i');
	FCD_LCDDisplay0_PrintASCII('t');
	FCD_LCDDisplay0_PrintASCII(' ');
	FCD_LCDDisplay0_PrintASCII('m');
	FCD_LCDDisplay0_PrintASCII('y');
	FCD_LCDDisplay0_PrintASCII(' ');
	FCD_LCDDisplay0_PrintASCII('s');
	FCD_LCDDisplay0_PrintASCII('w');
	FCD_LCDDisplay0_PrintASCII('i');
	FCD_LCDDisplay0_PrintASCII('t');
	FCD_LCDDisplay0_PrintASCII('c');
	FCD_LCDDisplay0_PrintASCII('h');
	FCD_LCDDisplay0_PrintASCII('e');
	FCD_LCDDisplay0_PrintASCII('s');

	//Loop
	//Loop: While 1
	while (1)
	{

		//Call Component Macro
		//Call Component Macro: ScrollDisplay(0, 1)
		FCD_LCDDisplay0_ScrollDisplay(0, 1);

		//Delay
		//Delay: 200 ms
		delay_ms(200);

		//Call Component Macro
		//Call Component Macro: ClearLine(1)
		FCD_LCDDisplay0_ClearLine(1);

		//Input
		//Input: PORTE -> sel
		trise = trise | 0xFF;
		FCV_SEL = porte;

		//Decision
		//Decision: sel = 0?
		if (FCV_SEL == 0)
		{

			//Call Component Macro
			//Call Component Macro: Cursor(0, 1)
			FCD_LCDDisplay0_Cursor(0, 1);

			//Call Component Macro
			//Call Component Macro: PrintString("      Please select a mode")
			FCD_LCDDisplay0_PrintString("      Please select a mode", 26);

		} else {

			//Decision
			//Decision: sel = 1?
			if (FCV_SEL == 1)
			{

				//Call Component Macro
				//Call Component Macro: Cursor(1, 1)
				FCD_LCDDisplay0_Cursor(1, 1);

				//Call Component Macro
				//Call Component Macro: PrintString("Play Mode         Play Mode")
				FCD_LCDDisplay0_PrintString("Play Mode         Play Mode", 27);

			} else {

				//Decision
				//Decision: sel = 2?
				if (FCV_SEL == 2)
				{

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Call Component Macro
					//Call Component Macro: Cursor(7, 0)
					FCD_LCDDisplay0_Cursor(7, 0);

					//Call Component Macro
					//Call Component Macro: PrintASCII("I")
					FCD_LCDDisplay0_PrintASCII('I');

					//Delay
					//Delay: 200 ms
					delay_ms(200);

					//Input
					//Input: PORTE -> sel
					trise = trise | 0xFF;
					FCV_SEL = porte;

					//Decision
					//Decision: sel != 2?
					if (FCV_SEL != 2)
					{

						//Goto Connection Point
						//Goto Connection Point: [A]: A
						goto FCC_Main_A;

					// } else {

					}

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Call Component Macro
					//Call Component Macro: Cursor(2, 1)
					FCD_LCDDisplay0_Cursor(2, 1);

					//Call Component Macro
					//Call Component Macro: PrintASCII("Interactive")
					FCD_LCDDisplay0_PrintASCII('I');
					FCD_LCDDisplay0_PrintASCII('n');
					FCD_LCDDisplay0_PrintASCII('t');
					FCD_LCDDisplay0_PrintASCII('e');
					FCD_LCDDisplay0_PrintASCII('r');
					FCD_LCDDisplay0_PrintASCII('a');
					FCD_LCDDisplay0_PrintASCII('c');
					FCD_LCDDisplay0_PrintASCII('t');
					FCD_LCDDisplay0_PrintASCII('i');
					FCD_LCDDisplay0_PrintASCII('v');
					FCD_LCDDisplay0_PrintASCII('e');

					//Delay
					//Delay: 200 ms
					delay_ms(200);

					//Input
					//Input: PORTE -> sel
					trise = trise | 0xFF;
					FCV_SEL = porte;

					//Decision
					//Decision: sel != 2?
					if (FCV_SEL != 2)
					{

						//Goto Connection Point
						//Goto Connection Point: [A]: A
						goto FCC_Main_A;

					// } else {

					}

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Call Component Macro
					//Call Component Macro: Cursor(7, 0)
					FCD_LCDDisplay0_Cursor(7, 0);

					//Call Component Macro
					//Call Component Macro: PrintASCII("A")
					FCD_LCDDisplay0_PrintASCII('A');

					//Delay
					//Delay: 200 ms
					delay_ms(200);

					//Input
					//Input: PORTE -> sel
					trise = trise | 0xFF;
					FCV_SEL = porte;

					//Decision
					//Decision: sel != 2?
					if (FCV_SEL != 2)
					{

						//Goto Connection Point
						//Goto Connection Point: [A]: A
						goto FCC_Main_A;

					// } else {

					}

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Call Component Macro
					//Call Component Macro: Cursor(5, 1)
					FCD_LCDDisplay0_Cursor(5, 1);

					//Call Component Macro
					//Call Component Macro: PrintASCII("Audio")
					FCD_LCDDisplay0_PrintASCII('A');
					FCD_LCDDisplay0_PrintASCII('u');
					FCD_LCDDisplay0_PrintASCII('d');
					FCD_LCDDisplay0_PrintASCII('i');
					FCD_LCDDisplay0_PrintASCII('o');

					//Delay
					//Delay: 200 ms
					delay_ms(200);

					//Input
					//Input: PORTE -> sel
					trise = trise | 0xFF;
					FCV_SEL = porte;

					//Decision
					//Decision: sel != 2?
					if (FCV_SEL != 2)
					{

						//Goto Connection Point
						//Goto Connection Point: [A]: A
						goto FCC_Main_A;

					// } else {

					}

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Call Component Macro
					//Call Component Macro: Cursor(7, 0)
					FCD_LCDDisplay0_Cursor(7, 0);

					//Call Component Macro
					//Call Component Macro: PrintASCII("M")
					FCD_LCDDisplay0_PrintASCII('M');

					//Delay
					//Delay: 200 ms
					delay_ms(200);

					//Input
					//Input: PORTE -> sel
					trise = trise | 0xFF;
					FCV_SEL = porte;

					//Decision
					//Decision: sel != 2?
					if (FCV_SEL != 2)
					{

						//Goto Connection Point
						//Goto Connection Point: [A]: A
						goto FCC_Main_A;

					// } else {

					}

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Call Component Macro
					//Call Component Macro: Cursor(3, 1)
					FCD_LCDDisplay0_Cursor(3, 1);

					//Call Component Macro
					//Call Component Macro: PrintASCII("Modulator")
					FCD_LCDDisplay0_PrintASCII('M');
					FCD_LCDDisplay0_PrintASCII('o');
					FCD_LCDDisplay0_PrintASCII('d');
					FCD_LCDDisplay0_PrintASCII('u');
					FCD_LCDDisplay0_PrintASCII('l');
					FCD_LCDDisplay0_PrintASCII('a');
					FCD_LCDDisplay0_PrintASCII('t');
					FCD_LCDDisplay0_PrintASCII('o');
					FCD_LCDDisplay0_PrintASCII('r');

					//Delay
					//Delay: 200 ms
					delay_ms(200);

					//Input
					//Input: PORTE -> sel
					trise = trise | 0xFF;
					FCV_SEL = porte;

					//Decision
					//Decision: sel != 2?
					if (FCV_SEL != 2)
					{

						//Goto Connection Point
						//Goto Connection Point: [A]: A
						goto FCC_Main_A;

					// } else {

					}

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Call Component Macro
					//Call Component Macro: Cursor(14, 0)
					FCD_LCDDisplay0_Cursor(14, 0);

					//Call Component Macro
					//Call Component Macro: PrintString("Interactive     Modulator")
					FCD_LCDDisplay0_PrintString("Interactive     Modulator", 25);

					//Call Component Macro
					//Call Component Macro: Cursor(24, 1)
					FCD_LCDDisplay0_Cursor(24, 1);

					//Call Component Macro
					//Call Component Macro: PrintASCII("{Audio}")
					FCD_LCDDisplay0_PrintASCII('{');
					FCD_LCDDisplay0_PrintASCII('A');
					FCD_LCDDisplay0_PrintASCII('u');
					FCD_LCDDisplay0_PrintASCII('d');
					FCD_LCDDisplay0_PrintASCII('i');
					FCD_LCDDisplay0_PrintASCII('o');
					FCD_LCDDisplay0_PrintASCII('}');

					//Loop
					//Loop: Loop 38 times
					for (FCLV_LOOP1=0; FCLV_LOOP1<38; FCLV_LOOP1++)
					{

						//Input
						//Input: PORTE -> sel
						trise = trise | 0xFF;
						FCV_SEL = porte;

						//Decision
						//Decision: sel != 2?
						if (FCV_SEL != 2)
						{

							//Goto Connection Point
							//Goto Connection Point: [A]: A
							goto FCC_Main_A;

						} else {

							//Call Component Macro
							//Call Component Macro: ScrollDisplay(0, 1)
							FCD_LCDDisplay0_ScrollDisplay(0, 1);

							//Delay
							//Delay: 100 ms
							delay_ms(100);

						}


					}

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Delay
					//Delay: 200 ms
					delay_ms(200);

					//Input
					//Input: PORTE -> sel
					trise = trise | 0xFF;
					FCV_SEL = porte;

					//Decision
					//Decision: sel != 2?
					if (FCV_SEL != 2)
					{

						//Goto Connection Point
						//Goto Connection Point: [A]: A
						goto FCC_Main_A;

					// } else {

					}

					//Call Component Macro
					//Call Component Macro: Cursor(0, 0)
					FCD_LCDDisplay0_Cursor(0, 0);

					//Call Component Macro
					//Call Component Macro: PrintASCII("3 Modes")
					FCD_LCDDisplay0_PrintASCII('3');
					FCD_LCDDisplay0_PrintASCII(' ');
					FCD_LCDDisplay0_PrintASCII('M');
					FCD_LCDDisplay0_PrintASCII('o');
					FCD_LCDDisplay0_PrintASCII('d');
					FCD_LCDDisplay0_PrintASCII('e');
					FCD_LCDDisplay0_PrintASCII('s');

					//Delay
					//Delay: 100 ms
					delay_ms(100);

					//Loop
					//Loop: Loop 20 times
					for (FCLV_LOOP2=0; FCLV_LOOP2<20; FCLV_LOOP2++)
					{

						//Input
						//Input: PORTE -> sel
						trise = trise | 0xFF;
						FCV_SEL = porte;

						//Decision
						//Decision: sel != 2?
						if (FCV_SEL != 2)
						{

							//Goto Connection Point
							//Goto Connection Point: [A]: A
							goto FCC_Main_A;

						// } else {

						}

						//Call Component Macro
						//Call Component Macro: ScrollDisplay(1, 1)
						FCD_LCDDisplay0_ScrollDisplay(1, 1);

						//Delay
						//Delay: 100 ms
						delay_ms(100);


					}

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Call Component Macro
					//Call Component Macro: Cursor(12, 0)
					FCD_LCDDisplay0_Cursor(12, 0);

					//Call Component Macro
					//Call Component Macro: PrintASCII("Demo")
					FCD_LCDDisplay0_PrintASCII('D');
					FCD_LCDDisplay0_PrintASCII('e');
					FCD_LCDDisplay0_PrintASCII('m');
					FCD_LCDDisplay0_PrintASCII('o');

					//Delay
					//Delay: 200 ms
					delay_ms(200);

					//Input
					//Input: PORTE -> sel
					trise = trise | 0xFF;
					FCV_SEL = porte;

					//Decision
					//Decision: sel != 2?
					if (FCV_SEL != 2)
					{

						//Goto Connection Point
						//Goto Connection Point: [A]: A
						goto FCC_Main_A;

					// } else {

					}

					//Call Component Macro
					//Call Component Macro: Cursor(6, 1)
					FCD_LCDDisplay0_Cursor(6, 1);

					//Call Component Macro
					//Call Component Macro: PrintASCII("Play")
					FCD_LCDDisplay0_PrintASCII('P');
					FCD_LCDDisplay0_PrintASCII('l');
					FCD_LCDDisplay0_PrintASCII('a');
					FCD_LCDDisplay0_PrintASCII('y');

					//Delay
					//Delay: 200 ms
					delay_ms(200);

					//Input
					//Input: PORTE -> sel
					trise = trise | 0xFF;
					FCV_SEL = porte;

					//Decision
					//Decision: sel != 2?
					if (FCV_SEL != 2)
					{

						//Goto Connection Point
						//Goto Connection Point: [A]: A
						goto FCC_Main_A;

					// } else {

					}

					//Call Component Macro
					//Call Component Macro: Cursor(1, 0)
					FCD_LCDDisplay0_Cursor(1, 0);

					//Call Component Macro
					//Call Component Macro: PrintASCII("SFX")
					FCD_LCDDisplay0_PrintASCII('S');
					FCD_LCDDisplay0_PrintASCII('F');
					FCD_LCDDisplay0_PrintASCII('X');

					//Delay
					//Delay: 250 ms
					delay_ms(250);

					//Loop
					//Loop: Loop 3 times
					for (FCLV_LOOP3=0; FCLV_LOOP3<3; FCLV_LOOP3++)
					{

						//Input
						//Input: PORTE -> sel
						trise = trise | 0xFF;
						FCV_SEL = porte;

						//Decision
						//Decision: sel != 2?
						if (FCV_SEL != 2)
						{

							//Goto Connection Point
							//Goto Connection Point: [A]: A
							goto FCC_Main_A;

						// } else {

						}

						//Call Component Macro
						//Call Component Macro: ScrollDisplay(0, 1)
						FCD_LCDDisplay0_ScrollDisplay(0, 1);

						//Delay
						//Delay: 200 ms
						delay_ms(200);

						//Call Component Macro
						//Call Component Macro: ScrollDisplay(1, 1)
						FCD_LCDDisplay0_ScrollDisplay(1, 1);

						//Delay
						//Delay: 200 ms
						delay_ms(200);


					}

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Call Component Macro
					//Call Component Macro: Cursor(6, 0)
					FCD_LCDDisplay0_Cursor(6, 0);

					//Call Component Macro
					//Call Component Macro: PrintASCII("1 0")
					FCD_LCDDisplay0_PrintASCII('1');
					FCD_LCDDisplay0_PrintASCII(' ');
					FCD_LCDDisplay0_PrintASCII('0');

					//Delay
					//Delay: 200 ms
					delay_ms(200);

					//Call Component Macro
					//Call Component Macro: Cursor(7, 1)
					FCD_LCDDisplay0_Cursor(7, 1);

					//Call Component Macro
					//Call Component Macro: PrintASCII("3 2")
					FCD_LCDDisplay0_PrintASCII('3');
					FCD_LCDDisplay0_PrintASCII(' ');
					FCD_LCDDisplay0_PrintASCII('2');

					//Delay
					//Delay: 350 ms
					delay_ms(255);
					delay_ms(95);

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Call Component Macro
					//Call Component Macro: Cursor(14, 0)
					FCD_LCDDisplay0_Cursor(14, 0);

					//Call Component Macro
					//Call Component Macro: PrintASCII("IAM")
					FCD_LCDDisplay0_PrintASCII('I');
					FCD_LCDDisplay0_PrintASCII('A');
					FCD_LCDDisplay0_PrintASCII('M');

					//Call Component Macro
					//Call Component Macro: Cursor(26, 1)
					FCD_LCDDisplay0_Cursor(26, 1);

					//Call Component Macro
					//Call Component Macro: PrintASCII("1302")
					FCD_LCDDisplay0_PrintASCII('1');
					FCD_LCDDisplay0_PrintASCII('3');
					FCD_LCDDisplay0_PrintASCII('0');
					FCD_LCDDisplay0_PrintASCII('2');

					//Loop
					//Loop: Loop 14 times
					for (FCLV_LOOP4=0; FCLV_LOOP4<14; FCLV_LOOP4++)
					{

						//Input
						//Input: PORTE -> sel
						trise = trise | 0xFF;
						FCV_SEL = porte;

						//Decision
						//Decision: sel != 2?
						if (FCV_SEL != 2)
						{

							//Goto Connection Point
							//Goto Connection Point: [A]: A
							goto FCC_Main_A;

						// } else {

						}

						//Call Component Macro
						//Call Component Macro: ScrollDisplay(0, 1)
						FCD_LCDDisplay0_ScrollDisplay(0, 1);

						//Delay
						//Delay: 200 ms
						delay_ms(200);


					}

					//Delay
					//Delay: 500 ms
					delay_ms(255);
					delay_ms(245);

					//Call Component Macro
					//Call Component Macro: Clear()
					FCD_LCDDisplay0_Clear();

					//Input
					//Input: PORTE -> sel
					trise = trise | 0xFF;
					FCV_SEL = porte;

					//Decision
					//Decision: sel != 2?
					if (FCV_SEL != 2)
					{

						//Connection Point
						//Connection Point: [A]: A
FCC_Main_A:
;

						//Call Component Macro
						//Call Component Macro: Clear()
						FCD_LCDDisplay0_Clear();

						//Call Component Macro
						//Call Component Macro: Cursor(1, 0)
						FCD_LCDDisplay0_Cursor(1, 0);

						//Call Component Macro
						//Call Component Macro: PrintASCII("Hi, I am IAM1302. Hit my switches")
						FCD_LCDDisplay0_PrintASCII('H');
						FCD_LCDDisplay0_PrintASCII('i');
						FCD_LCDDisplay0_PrintASCII(',');
						FCD_LCDDisplay0_PrintASCII(' ');
						FCD_LCDDisplay0_PrintASCII('I');
						FCD_LCDDisplay0_PrintASCII(' ');
						FCD_LCDDisplay0_PrintASCII('a');
						FCD_LCDDisplay0_PrintASCII('m');
						FCD_LCDDisplay0_PrintASCII(' ');
						FCD_LCDDisplay0_PrintASCII('I');
						FCD_LCDDisplay0_PrintASCII('A');
						FCD_LCDDisplay0_PrintASCII('M');
						FCD_LCDDisplay0_PrintASCII('1');
						FCD_LCDDisplay0_PrintASCII('3');
						FCD_LCDDisplay0_PrintASCII('0');
						FCD_LCDDisplay0_PrintASCII('2');
						FCD_LCDDisplay0_PrintASCII('.');
						FCD_LCDDisplay0_PrintASCII(' ');
						FCD_LCDDisplay0_PrintASCII('H');
						FCD_LCDDisplay0_PrintASCII('i');
						FCD_LCDDisplay0_PrintASCII('t');
						FCD_LCDDisplay0_PrintASCII(' ');
						FCD_LCDDisplay0_PrintASCII('m');
						FCD_LCDDisplay0_PrintASCII('y');
						FCD_LCDDisplay0_PrintASCII(' ');
						FCD_LCDDisplay0_PrintASCII('s');
						FCD_LCDDisplay0_PrintASCII('w');
						FCD_LCDDisplay0_PrintASCII('i');
						FCD_LCDDisplay0_PrintASCII('t');
						FCD_LCDDisplay0_PrintASCII('c');
						FCD_LCDDisplay0_PrintASCII('h');
						FCD_LCDDisplay0_PrintASCII('e');
						FCD_LCDDisplay0_PrintASCII('s');

						//Delay
						//Delay: 100 ms
						delay_ms(100);

					// } else {

					}

				} else {

					//Decision
					//Decision: sel = 4?
					if (FCV_SEL == 4)
					{

						//Call Component Macro
						//Call Component Macro: Cursor(1, 1)
						FCD_LCDDisplay0_Cursor(1, 1);

						//Call Component Macro
						//Call Component Macro: PrintString("SFX Mode          SFX Mode")
						FCD_LCDDisplay0_PrintString("SFX Mode          SFX Mode", 26);

					} else {

						//Call Component Macro
						//Call Component Macro: Cursor(1, 1)
						FCD_LCDDisplay0_Cursor(1, 1);

						//Call Component Macro
						//Call Component Macro: PrintString("Error, Pick one switch at a time")
						FCD_LCDDisplay0_PrintString("Error, Pick one switch at a time", 32);

					}

				}

			}

		}


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



